kafka:
  bootstrap-server: localhost:9092
  consumer:
    group-id: aggregator-group
    max-poll-records: 100
    fetch-max-bytes: 3072000
    max-partition-fetch-bytes: 307200
    max-poll-interval-ms: 300000
    session-timeout-ms: 45000
    enable-auto-commit: false
    auto-offset-reset: earliest
    auto-commit-interval-ms: 5000
  producer:
    acks: all
    retries: 3
    max-in-flight-requests-per-connection: 1
  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1
server:
  port: 8081
