collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.serialization.GeneralAvroSerializer
        acks: all
        retries: 3
        max.in.flight.requests.per.connection: 1
        linger.ms: 0
      topics:
        sensors-events: telemetry.sensors.v1
        hubs-events: telemetry.hubs.v1
server:
  port: 8080
grpc:
  server:
    port: 9090
