server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: "http://localhost:8081"
        auto.register.schemas: "true"
    properties:
      schema.registry.url: "http://localhost:8081"

logging:
  level:
    ru.yandex.practicum.collector: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO