spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer?currentSchema=payment
    username: postgres
    password: postgres
