kafka.bootstrap-server=localhost:9092
kafka.consumer.group-id=aggregator-group
kafka.consumer.max-poll-records=100
kafka.consumer.fetch-max-bytes=3072000
kafka.consumer.max-partition-fetch-bytes=307200
kafka.consumer.max-poll-interval-ms=300000
kafka.consumer.session-timeout-ms=45000
kafka.consumer.enable-auto-commit=false
kafka.consumer.auto-offset-reset=earliest
kafka.consumer.auto-commit-interval-ms=5000
kafka.producer.acks=all
kafka.producer.retries=3
kafka.producer.max-in-flight-requests-per-connection=1
kafka.topics.sensors=telemetry.sensors.v1
kafka.topics.snapshots=telemetry.snapshots.v1
server.port=8081
