kafka.bootstrap-servers=localhost:9092

kafka.consumer.snapshots.group-id=analyzer-snapshot-group
kafka.consumer.snapshots.max-poll-records=100
kafka.consumer.snapshots.enable-auto-commit=false
kafka.consumer.snapshots.auto-offset-reset=earliest
kafka.topic.snapshots=telemetry.snapshots.v1

kafka.consumer.hubs.group-id=analyzer-hub-group
kafka.consumer.hubs.max-poll-records=10
kafka.consumer.hubs.enable-auto-commit=false
kafka.consumer.hubs.auto-offset-reset=earliest
kafka.consumer.hubs.auto-commit-interval-ms=5000
kafka.topic.hubs=telemetry.hubs.v1

spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext

server.port=8082

grpc.server.port=-1
spring.sql.init.mode=always
